// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rphpgrfrceumxxmlzmvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwaHBncmZyY2V1bXh4bWx6bXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzMwMTksImV4cCI6MjA2NDgwOTAxOX0.ZQ6zCbv-T1v9zTyjDRv9dw7LJkhzRyCKXYsZhxAYLdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);